### ISSUE TITLE
Create requirements / README just like isobib

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/gbbib#1]
Index: http://www.gb688.cn/bzgk/gb/index

* the index page for Chinese GB standards.

Single standard: e.g., http://www.gb688.cn/bzgk/gb/newGbInfo?hcno=3EE019B0135404CE790692FAF5E6A85E

<img width="950" alt="screen shot 2018-03-21 at 12 45 18 am" src="https://user-images.githubusercontent.com/11865/37669185-274b35dc-2ca1-11e8-81ea-b29a8da33162.png">

Includes the following data:

* Standard number: GB/T 35890-2018
* Chinese title: "高通量测序数据序列格式规范"
* English title: "Technical specification of high throughput sequencing data format"

* CCS (Chinese Classification System): "A40"
* ICS: "07.080"
* Publishing Date: "2018-02-06"
* Activation Date: "2018-09-01"
* Managing Entity: 国家标准化管理委员会
* Authoritative Entity: 全国生化检测标准化技术委员会
* Publishing Entity(ies): 中华人民共和国国家质量监督检验检疫总局 and 中国国家标准化管理委员会

**Comment by ronaldtse** [comment]
* "GB/T" means "Recommended standard"
* "GB/Z" means "Guidelines"
* "GB" means "Mandatory standard"

**Comment by ronaldtse** [comment]
See https://github.com/riboseinc/gbdoc for model details.

**Comment by ronaldtse** [comment]
Actually we should use this newer platform that provides more information:

http://www.std.gov.cn/gb/search/gbDetailed?id=64852AEA5AE5F437E05397BE0A0A3540

<img width="719" alt="screen shot 2018-03-29 at 10 48 25 am" src="https://user-images.githubusercontent.com/11865/38065524-bd5619cc-333e-11e8-8bb4-ef828793ce97.png">

<img width="725" alt="screen shot 2018-03-29 at 10 47 22 am" src="https://user-images.githubusercontent.com/11865/38065518-b285bd7c-333e-11e8-8524-8a433685cbc5.png">

**Comment by andrew2net** [comment]
so we need a gem similar to Isobib, do we?

**Comment by ronaldtse** [comment]
@andrew2net yes indeed -- this is the repo for it, called GbBib.

**Comment by ronaldtse** [comment]
@andrew2net could you help update the README to explain how to use this gem? Thanks.
