### ISSUE TITLE
create gbbib_get() method

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/gbbib#11]
gbbib needs an external facing gbbib_get(code, year, opts) method, patterned after the newly added isobib_get(code, year, opts) method of isobib, to hide all the innards of the Hits Collections. This should be a straightforward port.

asciidoctor-iso uses the isobib_get() method now, and asciidoctor-gb, being a subclass of asciidoctor-iso, is going to look up Isobib::IsoBibliography.isobib_get(code, year, opts) and Gbbib::GbBibliography.gbbib_get(code, year, opts) together.

**Comment by ronaldtse** [comment]
Could we just have a generically named “get” method rather than “gbbib_get”?

**Comment by opoudjis** [comment]
*shrug* sure. Will change isobib.

**Comment by ronaldtse** [comment]
Thank you!

**Comment by andrew2net** [comment]
@opoudjis should I implement the method?

**Comment by opoudjis** [comment]
If you don't mind, sure

**Comment by andrew2net** [comment]
@opoudjis ok, I will

**Comment by andrew2net** [comment]
@opoudjis do we have part/all-parts in GbBib?

**Comment by opoudjis** [comment]
I assume we do, since GB documents do have parts, and Ronald provided a translation for "all parts" in Chinese. @ronaldtse?

**Comment by ronaldtse** [comment]
Yes there are, it's just like ISO. Thanks!

**Comment by andrew2net** [comment]
@ronaldtse can't find any document with part-number. Could you help?

**Comment by andrew2net** [comment]
@ronaldtse is `GB 5606.2-2005` part-number 2?

**Comment by ronaldtse** [comment]
Yes! The delimiters are different from ISO, where the DOT is the pet delimiter, the HYPHEN is the year delimiter.
