### ISSUE TITLE
Integrate into relaton

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/gbbib#13]
And Asciidoctor-ISO and Asciidoctor-GB

**Comment by opoudjis** [comment]
I have not started, so go ahead

**Comment by andrew2net** [comment]
done

**Comment by opoudjis** [comment]
Not quite; at a minimum, from_xml will need to be inherited, and adjusted to any RFC XML specific adjustments made for GbBibliographicItem—so that we can be sure that caching GB entries roundtrips all the information we've put into the XML. Will need that confirmed in rspec, as I have added to the iso-bib-item instance:

````
  it 'create IsoBibliographicItem from XML' do
    xml = File.read 'spec/examples/iso_bib_item.xml'
    item = IsoBibItem.from_xml xml
    expect(item).to be_instance_of IsoBibItem::IsoBibliographicItem
    expect(item.to_xml).to be_equivalent_to xml
  end
````

**Comment by andrew2net** [comment]
@opoudjis Eventually I didn't use to_xml/from_xml methods to cache items. PStore can save and read instances of classes without the serialization methods. I don't know what method it uses but it works perfectly.
Do you think we need to use to_xml/from_xml methods?

**Comment by opoudjis** [comment]
Hm. I think we'll need it eventually for import purposes, but I understand, we don't need it for caching. OK. Leave this ticket open for my testing.

**Comment by opoudjis** [comment]
Fixed handling of titles, added "GB Standard prefix".

**Comment by opoudjis** [comment]
To do: 
* Integrate into asciidoctor-iso. 
* Integrate into asciidoctor-gb (supplying prefix "GB Standard" for recognised GB standard codes)

**Comment by andrew2net** [comment]
@opoudjis starting to do it

**Comment by andrew2net** [comment]
@opoudjis what do we need to integrate into asciidoctor-iso/gb?

**Comment by opoudjis** [comment]
I'm doing it now.

**Comment by opoudjis** [comment]
I have now integrated GB into asciidoctor-iso (making sure that it passes all non-ISO references through relaton before continuing processing), and asciidoctor-gb (as above, and prefixing the code request from relaton with "GB Standard".) I now need to finish testing on the GB side, after which I will close this ticket.
