### ISSUE TITLE
Status is single item

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/gbbib#14]
We noted in https://github.com/riboseinc/iso-bib-item/issues/1#issuecomment-403237868 that for ISO bibliographic items status is a stage and a substage, while for other standards types, status is a single item.

Status is a single item for GB. Currently the gem is assuming that it follows ISO in having a stage and a substage, hence the rspec is failing:

````
       -  <status>activated</status>
       +  <status>
       +    <stage/>
       +    <substage/>
       +  </status>
````

I see that in isobib, `fetch_status()` returns `{ status: status, stage: stage, substage: substage }`. This should be able to deal with the difference: Gbbib should be populating status instead of stage/substage, and the serialisation to ISOXML should pick either the status or the stage/substage, depending on which is present.

**Comment by andrew2net** [comment]
@opoudjis I did it in the last commit. https://github.com/riboseinc/iso-bib-item/commit/78fc91df2068c2ef68b2b5b8fea457690f481ac8
It needs to make a new release and update iso-bib-item in Gbbib.

**Comment by andrew2net** [comment]
done
