### ISSUE TITLE
GB technical committee type

### ISSUE THREAD

**Issue by andrew2net** [riboseinc/gbbib#6]
@ronaldtse do you know where to scrape `GbTechniclaCommittee`? The value should be `technical` or `provisional`.

**Comment by andrew2net** [comment]
@ronaldtse also I can't find where to scripe `GbBibliographicItem.topic`

**Comment by ronaldtse** [comment]
e.g. on this page: http://www.std.gov.cn/gb/search/gbDetailed?id=6747E1059F9DC35AE05397BE0A0A017F

You can see "TC513" is the technical committee. Its link brings you to http://www.std.gov.cn/search/orgDetailView?tcCode=TC513 which provides details of this TC.

I can't seem to find the `topic` on the pages too.

**Comment by ronaldtse** [comment]
A set of similar details are found here on the SAC site:

http://www.sac.gov.cn/was5/web/outlinetemplet/gjbzcx.jsp

Enter the standard number ("GB/T 20223") and click search:

http://www.sac.gov.cn/was5/web/search?channelid=97779&templet=gjcxjg_detail.jsp&searchword=STANDARD_CODE=%27GB/T%2020223-2018%27&XZ=T&STANDARD_CODE=GB/T%2020223-2018

There is still no `topic` though.

**Comment by ronaldtse** [comment]
@andrew2net you’re right. Can you file a ticket in the model repo to accept an organization instead of a TC? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse yes I can. What would the organization be for http://www.ttbz.org.cn/StandardManage/Detail/22746/? Assume Issuing authority (发证机关) is what we need, is it?

**Comment by ronaldtse** [comment]
Let me map here. All of the following fields are applicable.

The table heading is:
* 团体详细信息 (Organization detailed information)


团体名称 (Organization name):
* 广州环境保护产业协会


登记证号 (Registration number):
* 51440100517355015H

发证机关 (Issuing authority):
* 广州市民政局

业务范围 (Scope of activity):
* 协助政府制定环保产业规划标准与规范、环保产品服务质量监管与评定，开展展览交流与培训、技术服务与咨询，环境服务专项资格证核发。

法定代表人/负责人 (Authorized representative):
* 戴自觉

依托单位名称 (Dependent organization name):
* (empty)

通讯地址 (Communication address):
* 广州市越秀区光塔路仙邻巷50号三楼

邮编 (Postal number):
* 510180

**Comment by andrew2net** [comment]
oh, I see, Google translates 团体名称 as "Group name", but 团体 can but translate as "Organization" either.
And I have a question about TC type. How to detect which is `technical` and which `provisional`?

**Comment by ronaldtse** [comment]
For TC type, published documents should all be `technical`. In addition, instead of `provisional`, it should be "Project Committee" rather than "Provisional Committee".

**Comment by andrew2net** [comment]
@ronaldtse where scrape TC for Sector Standard http://www.std.gov.cn/hb/search/stdHBDetailed?id=6BC3AD94A1728ABCE05397BE0A0A5667?

**Comment by ronaldtse** [comment]
On this given example, there is this text:


```
(Title)
叉车属具 软包夹

Tags:
{行业标准 (Sector standard) JB 机械 (JB, machinery)}
{推荐性 (Recommendation)}
{现行 (Active)}

行业标准《叉车属具 软包夹》，主管部门为 _工业和信息化部_。 (this is the "supervising department")
(Sector standard 叉车属具 软包夹, supervising department is 工业和信息化部)

目录 (table of contents) 

1标准状态 (standard status)

发布于 2018-02-09 (publish date on 2018-02-09)
实施于 2018-10-01 (implementation date on 2018-10-01)
废止 (revocation date: none)

2基础信息 (basic information)
标准号 (Standard identifier): JB/T 13368-2018 
发布日期 (Publish date): 2018-02-09
实施日期 (Implementation date): 2018-10-01
中国标准分类号 (CCS code): J83
国际标准分类号 (ICS code): 53.06  
主管部门 (Supervising department): 工业和信息化部 (ministry of industry and information technology)
行业分类 (Industry category): 制造业 (manufacturing)

3备案信息 (Filing information)

备案信息 (filing information)
备案号 (filing number)：61715-2018
备案公告 (filing announcement)： 2018年第4号 。 (Number 4, 2018. [comes with the actual link to announcement])

4相近标准(计划) (related standards (and plans))
JB/T 3340-2005  插腿式叉车
GB/T 5183-2005  叉车 货叉 尺寸
...

```

**Comment by ronaldtse** [comment]
In sector standards, there are no TCs -- there is the "Administration" which is listed here:  https://github.com/riboseinc/gbdoc/blob/master/models/gb-standard-sector-prefix.adoc

**Comment by andrew2net** [comment]
@ronaldtse LY code is Forestry here:
https://github.com/riboseinc/gbdoc/blob/master/models/gb-standard-sector-prefix.adoc
but there is a prefix SL_forestry in GbDoc Models
https://github.com/riboseinc/gbdoc#gbdoc-models
assume SL_forestry is related to SL code, but SL code is Water resources. Is it correct?

**Comment by ronaldtse** [comment]
@andrew2net yes you're right -- LY is for Forestry. I've fixed the mistake (and a few more) in GbDoc model image now. (https://github.com/riboseinc/gbdoc/commit/2f16b976d529de22e94af157503d3cca65c306ce)

**Comment by andrew2net** [comment]
@ronaldtse looks like QC_automobile is a mistake also. QC is Automotive in https://github.com/riboseinc/gbdoc/blob/master/models/gb-standard-sector-prefix.adoc

**Comment by opoudjis** [comment]
@ronaldtse my source of Truth for prefixes has been the document, not the image. I assume the document remains correct?

**Comment by ronaldtse** [comment]
Yes, the document is supposed to be correct.

**Comment by ronaldtse** [comment]
Fixed QC_automotive in model too.
