### ISSUE TITLE
Fetched XML should contain CCS and ICS codes in addition to text

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/gbbib#9]
`<ccs>` and `<ics>` codes should contain the CCS / ICS numbers in addition to text.

They should rely on:
* https://github.com/riboseinc/isoics
* https://github.com/riboseinc/cnccs

**Comment by andrew2net** [comment]
@ronaldtse gbstandard.rng defines ccs XML element as:
```
  <define name="gbccs">
    <element name="ccs">
      <text/>
    </element>
  </define>
```
and isostandard.rng defines ics XML element as:
```
  <define name="ics">
    <element name="ics">
      <text/>
    </element>
  </define>
```
So with existed XML schema we can place only one text field to ccs/ics element. Do you mean conctenting number and text? i.e. `<ics>67.060 Cereals, pulses and derived products</ics>`

**Comment by ronaldtse** [comment]
The RNG should follow the model definition in https://github.com/riboseinc/isodoc (Ics model) and https://github.com/riboseinc/gbdoc (Ccs model).

It is very possible that the RNG files are slightly different -- could you help update them too?

Thanks.

**Comment by andrew2net** [comment]
done
